# 配置MySQL数据库的连接参数
spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/kemao_1?useSSL=false&serverTimezone=CST&allowPublicKeyRetrieval=true
      username: kemao_1
      password: 1234
   # JPA配置
   jpa:
      #database-platform: MySQL57
      #showSql: true
      hibernate:
         # 属性的名称为ddlAuto，可以直接使用ddlAuto名称，也可以把字母全改为小写，使用减号隔开
         ddl-auto: update
      properties:
         # Hibernate的方言参考官方的hibernate.cfg.xml文件中的配置
         hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      # 在一个请求里面打开一个EntityManager，这样可以让实体对象传递给JSP以后，还能够使用懒加载
      # 如果EntityManager被关闭，页面上肯定不能使用懒加载从数据库加载关联数据
      openInView: true

   # 配置Redis的连接信息
   redis:
      # 这里换自己的IP
      host: 127.0.0.1
      port: 6379
      database: 15

   

# 修改运行时的端口号，因为一个端口号只能被一个人使用。
# 如果多个人使用一台服务器，自然要使用不同的端口！
server.port: 9089
