# 配置MySQL数据库的连接参数
spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/xingqi_3?useSSL=false&serverTimezone=CST&allowPublicKeyRetrieval=true
      username: xingqi_3
      password: 1234
   jpa:
# 自动生产DDL语句（数据定义语言），用于实现表结构自动创建
      generate-ddl: true
# 显示每个SQL在日志里面
      show-sql: true
# 配置Redis的连接信息
   redis:
# 这里换自己的IP
      host: 120.78.3.25
      port: 6379
      database: 15
